async function loadGames() {
  const container = document.getElementById('scoreboard-grid');
  container.innerHTML = '<p style="text-align: center;">Loading FBS games...</p>';

  try {
    // Fetch data generated by GitHub Action (cache-busting query included)
    const response = await fetch('data.json?v=' + new Date().getTime());
    
    if (!response.ok) {
      throw new Error(`Data fetch failed (${response.status})`);
    }

    const data = await response.json();
    let events = data.events || [];

    if (events.length === 0) {
      container.innerHTML = '<p style="text-align: center;">No FBS games scheduled for this week.</p>';
      return;
    }

    // Sort: Upcoming/In-Progress games first, Completed (STATUS_FINAL) games at the bottom
    events.sort((a, b) => {
      const isACompleted = a.status?.type?.state === 'post';
      const isBCompleted = b.status?.type?.state === 'post';

      if (isACompleted && !isBCompleted) return 1;  // Move completed 'a' down
      if (!isACompleted && isBCompleted) return -1; // Keep upcoming 'a' up
      return new Date(a.date) - new Date(b.date);    // Otherwise sort chronologically
    });

    container.innerHTML = events.map(event => {
      const competition = event.competitions[0];
      const homeTeam = competition.competitors.find(c => c.homeAway === 'home');
      const awayTeam = competition.competitors.find(c => c.homeAway === 'away');
      
      const gameState = event.status?.type?.state; // 'pre', 'in', or 'post'
      const isCompleted = gameState === 'post';
      const isInProgress = gameState === 'in';

      // Extract TV broadcast network
      const broadcast = competition.broadcasts?.[0]?.names?.[0] || 'TV TBD';
      
      // Extract betting odds and spread
      const odds = competition.odds?.[0];
      const spread = odds?.details || 'Line: N/A';
      const overUnder = odds?.overUnder ? `O/U ${odds.overUnder}` : '';

      // Kickoff time or Final indicator
      let statusText = new Date(event.date).toLocaleString([], {
        weekday: 'short', month: 'numeric', day: 'numeric', hour: '2-digit', minute: '2-digit'
      });

      if (isCompleted) {
        statusText = 'FINAL';
      } else if (isInProgress) {
        statusText = event.status?.type?.detail || 'LIVE';
      }

      // Display score if live/final; otherwise display team record
      const homeScoreOrRecord = (isCompleted || isInProgress) 
        ? `<span class="score" style="font-weight: bold; font-size: 1rem;">${homeTeam.score || '0'}</span>` 
        : `<span class="record">${homeTeam.records?.[0]?.summary || ''}</span>`;

      const awayScoreOrRecord = (isCompleted || isInProgress) 
        ? `<span class="score" style="font-weight: bold; font-size: 1rem;">${awayTeam.score || '0'}</span>` 
        : `<span class="record">${awayTeam.records?.[0]?.summary || ''}</span>`;

      return `
        <div class="game-card ${isCompleted ? 'completed-game' : ''}">
          <div class="time-tv">
            <span class="time" style="${isCompleted ? 'color: #888;' : ''}">${statusText}</span>
            <span class="tv-badge">${broadcast}</span>
          </div>
          
          <div class="team home">
            <img src="${homeTeam.team.logo || ''}" alt="${homeTeam.team.displayName}" class="logo" style="width: 32px; height: 32px; object-fit: contain;">
            <div class="team-details">
              <span class="team-name">${homeTeam.team.displayName}</span>
            </div>
            ${homeScoreOrRecord}
          </div>

          <div class="team away">
            <img src="${awayTeam.team.logo || ''}" alt="${awayTeam.team.displayName}" class="logo" style="width: 32px; height: 32px; object-fit: contain;">
            <div class="team-details">
              <span class="team-name">${awayTeam.team.displayName}</span>
            </div>
            ${awayScoreOrRecord}
          </div>

          <div class="odds-bar">
            <span>${isCompleted ? 'Final Game' : `Odds: ${spread}`}</span>
            <span>${isCompleted ? '' : overUnder}</span>
          </div>
        </div>
      `;
    }).join('');

  } catch (error) {
    console.error('Failed to load scoreboard data:', error);
    container.innerHTML = `<p style="color: red; text-align: center;">Unable to load game data.</p>`;
  }
}

loadGames();
